In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('dataset/qsar_fish_toxicity.csv')
dataset.head(10)

    CIC0  SM1_Dz(Z)  GATS1i  NdsCH  NdssC  MLOGP  LC50 [-LOG(mol/L)]
0  3.260      0.829   1.676      0      1  1.453               3.770
1  2.189      0.580   0.863      0      0  1.348               3.115
2  2.125      0.638   0.831      0      0  1.348               3.531
3  3.027      0.331   1.472      1      0  1.807               3.510
4  2.094      0.827   0.860      0      0  1.886               5.390
5  3.222      0.331   2.177      0      0  0.706               1.819
6  3.179      0.000   1.063      0      0  2.942               3.947
7  3.000      0.000   0.938      1      0  2.851               3.513
8  2.620      0.499   0.990      0      0  2.942               4.402
9  2.834      0.134   0.950      0      0  1.591               3.021